on:
  push:
    branches:
      - master
      - next
  
  pull_request:
    branches:
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    name: Unittest and Build RPMs
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8                         
          architecture: x64

      - name: unittest

        run: |
            pip install pyyaml==5.3
            pip install httpretty
            pip install psutil
            pip install distro
            cd ./tests
            python -m unittest test_scylla_configure.py
            python -m unittest test_aws_instance.py
            python -m unittest test_gcp_instance.py

      - name: Build Centos 7 RPM
        run: docker run -v `pwd`:/scylla-machine-image -w /scylla-machine-image  --rm centos:7.2.1511 bash -c './dist/redhat/build_rpm.sh -t centos7'

      - name: Build Centos 8 RPM
        run: docker run -v `pwd`:/scylla-machine-image -w /scylla-machine-image  --rm rockylinux bash -c './dist/redhat/build_rpm.sh -t centos8'

      - name: Build Ubuntu DEB
        run: docker run -v `pwd`:/scylla-machine-image -w /scylla-machine-image  --rm ubuntu:20.04 bash -c './dist/debian/build_deb.sh'
